# Generated by Django 5.0.6 on 2024-06-20 00:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfaRegister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cfauser',
            name='siretNumber',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro de SIRET doit contenir exactement 14 chiffres.', regex='^\\d{14}$')]),
        ),
        migrations.CreateModel(
            name='sendStudentInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('lastname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('invitation_accepted', models.BooleanField(default=False)),
                ('cfa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
