# Generated by Django 5.0.6 on 2024-06-20 05:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfaRegister', '0002_alter_cfauser_siretnumber_sendstudentinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendstudentinvitation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
