# Generated by Django 5.0.6 on 2024-06-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfaRegister', '0003_sendstudentinvitation_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendstudentinvitation',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sendstudentinvitation',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sendstudentinvitation',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
