# Generated by Django 5.0.6 on 2024-06-20 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfaRegister', '0004_sendstudentinvitation_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sendstudentinvitation',
            old_name='date_of_birth',
            new_name='birthdate',
        ),
    ]
